# Generated by Django 2.0.7 on 2018-07-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='View1',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('barcode', models.CharField(db_column='Barcode', max_length=20)),
                ('date', models.DateField(db_column='Date')),
                ('qty', models.IntegerField(db_column='QTY')),
            ],
            options={
                'db_table': 'View_1',
                'managed': False,
            },
        ),
    ]
