# Generated by Django 2.0.7 on 2018-08-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_view1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vw_Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_desc', models.CharField(db_column='StoreDesc', max_length=100)),
                ('storeid', models.IntegerField(db_column='StoreID')),
                ('category', models.CharField(db_column='Category', max_length=10)),
                ('sales_amount', models.DecimalField(db_column='SalesAmount', decimal_places=2, max_digits=20)),
                ('sales_qty', models.IntegerField(db_column='SalesQty')),
                ('sales_price_avg', models.DecimalField(db_column='SalesPriceAvg', decimal_places=2, max_digits=20)),
                ('cost', models.DecimalField(db_column='Cost', decimal_places=2, max_digits=20)),
                ('sales_perc', models.DecimalField(db_column='SalesPerc', decimal_places=2, max_digits=20)),
                ('GM', models.DecimalField(db_column='GM', decimal_places=2, max_digits=20)),
                ('date', models.DateField(db_column='Date')),
            ],
            options={
                'db_table': 'vw_CategoryPerformance',
                'managed': False,
            },
        ),
    ]
