# Generated by Django 2.0.7 on 2018-08-16 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_vw_sales'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vw_sales',
            table='vw_Sales',
        ),
    ]
